spring:
  cloud:
    function:
      definition: producermotions;consumermotions
    stream:
      bindings:
        producermotions-out-0:
          destination: motions
          producer:
            useNativeEncoding: true
        consumermotions-in-0:
          destination: motions
          consumer:
            useNativeDecoding: true

      kafka:
        bindings:
          producermotions-out-0:
            producer:
              configuration:
                value.serializer: com.gitDeveloper2.cloudFunctions.MySerializer
          consumermotions-in-0:
            consumer:
              configuration:
                value.deserializer: com.gitDeveloper2.cloudFunctions.MyDeserializer
        binder:
          brokers:
            - localhost:9091
            - localhost:9092